import { jsPDF } from "jspdf";

import { formatDateTime } from "@/lib/productionTracker";
import type { JobOrder } from "@/types/order";

const PAGE_MARGIN = 40;
const FOOTER_HEIGHT = 28;
const LABEL_WIDTH = 132;
const ROW_GAP = 6;

function getDisplayValue(value?: string | null, fallback = "Not set") {
  const nextValue = value?.trim();
  return nextValue ? nextValue : fallback;
}

function buildFilename(orderId: string) {
  const safeId = orderId.trim().replace(/[^A-Za-z0-9-]+/g, "-");
  return `production-flow-${safeId || "job"}.pdf`;
}

function ensureSpace(doc: jsPDF, cursorY: number, heightNeeded: number) {
  const pageHeight = doc.internal.pageSize.getHeight();

  if (cursorY + heightNeeded <= pageHeight - FOOTER_HEIGHT - PAGE_MARGIN) {
    return cursorY;
  }

  doc.addPage();
  return PAGE_MARGIN;
}

function drawSectionTitle(doc: jsPDF, title: string, cursorY: number, width: number) {
  const nextY = ensureSpace(doc, cursorY, 30);

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(PAGE_MARGIN, nextY, width, 24, 8, 8, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(51, 65, 85);
  doc.text(title, PAGE_MARGIN + 12, nextY + 16);

  return nextY + 30;
}

function drawFieldRow(doc: jsPDF, label: string, value: string, cursorY: number, width: number) {
  const valueLines = doc.splitTextToSize(value, width - LABEL_WIDTH - 24);
  const rowHeight = Math.max(24, valueLines.length * 13 + 10);
  const nextY = ensureSpace(doc, cursorY, rowHeight + ROW_GAP);

  doc.setDrawColor(226, 232, 240);
  doc.line(PAGE_MARGIN, nextY + rowHeight, PAGE_MARGIN + width, nextY + rowHeight);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(label, PAGE_MARGIN + 8, nextY + 15);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(15, 23, 42);
  doc.text(valueLines, PAGE_MARGIN + LABEL_WIDTH, nextY + 15);

  return nextY + rowHeight + ROW_GAP;
}

async function loadImageForPdf(source: string) {
  return new Promise<{ dataUrl: string; width: number; height: number } | null>(
    (resolve) => {
      const image = new window.Image();

      if (!source.startsWith("data:image/")) {
        image.crossOrigin = "anonymous";
      }

      image.onload = () => {
        try {
          const canvas = document.createElement("canvas");
          canvas.width = image.naturalWidth;
          canvas.height = image.naturalHeight;

          const context = canvas.getContext("2d");

          if (!context) {
            resolve(null);
            return;
          }

          context.fillStyle = "#ffffff";
          context.fillRect(0, 0, canvas.width, canvas.height);
          context.drawImage(image, 0, 0);

          resolve({
            dataUrl: canvas.toDataURL("image/png"),
            width: image.naturalWidth,
            height: image.naturalHeight,
          });
        } catch {
          resolve(null);
        }
      };

      image.onerror = () => resolve(null);
      image.src = source;
    }
  );
}

function addFooter(doc: jsPDF) {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let pageNumber = 1; pageNumber <= pageCount; pageNumber += 1) {
    doc.setPage(pageNumber);
    doc.setDrawColor(226, 232, 240);
    doc.line(PAGE_MARGIN, pageHeight - FOOTER_HEIGHT, pageWidth - PAGE_MARGIN, pageHeight - FOOTER_HEIGHT);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(100, 116, 139);
    doc.text(
      "Generated by Production Flow",
      PAGE_MARGIN,
      pageHeight - 10
    );
    doc.text(
      `Page ${pageNumber} of ${pageCount}`,
      pageWidth - PAGE_MARGIN,
      pageHeight - 10,
      { align: "right" }
    );
  }
}

export async function generateJobPdf(order: JobOrder) {
  const doc = new jsPDF({
    format: "a4",
    unit: "pt",
  });
  const pageWidth = doc.internal.pageSize.getWidth();
  const contentWidth = pageWidth - PAGE_MARGIN * 2;
  const generatedAt = formatDateTime(new Date().toISOString());
  let cursorY = PAGE_MARGIN;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(15, 23, 42);
  doc.text("Production Flow", PAGE_MARGIN, cursorY + 10);
  doc.text("Job Record", pageWidth - PAGE_MARGIN, cursorY + 10, {
    align: "right",
  });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  doc.text("Production Flow - Job Record", PAGE_MARGIN, cursorY + 28);
  doc.text(`Job ID: ${order.id}`, pageWidth - PAGE_MARGIN, cursorY + 28, {
    align: "right",
  });
  doc.text(
    `Generated: ${generatedAt || new Date().toLocaleString("en-IE")}`,
    pageWidth - PAGE_MARGIN,
    cursorY + 42,
    { align: "right" }
  );

  cursorY += 60;
  doc.setDrawColor(203, 213, 225);
  doc.line(PAGE_MARGIN, cursorY, pageWidth - PAGE_MARGIN, cursorY);
  cursorY += 18;

  cursorY = drawSectionTitle(doc, "Core Job Details", cursorY, contentWidth);

  const detailRows: Array<[string, string]> = [
    ["Job ID", getDisplayValue(order.id)],
    ["Job Title", getDisplayValue(order.title)],
    ["Client", getDisplayValue(order.client)],
    ["Requested By", getDisplayValue(order.requestedBy)],
    ["Due Date / Due Text", getDisplayValue(order.due, "Pending")],
    ["Status", getDisplayValue(order.status)],
    ["Priority", getDisplayValue(order.priority)],
    ["Job Type", getDisplayValue(order.jobType)],
    ["Production Stage", getDisplayValue(order.productionStage)],
    ["Item / Project / Asset", getDisplayValue(order.itemProjectAsset)],
  ];

  for (const [label, value] of detailRows) {
    cursorY = drawFieldRow(doc, label, value, cursorY, contentWidth);
  }

  cursorY = drawSectionTitle(
    doc,
    "Work / Production Information",
    cursorY + 4,
    contentWidth
  );

  const productionRows: Array<[string, string]> = [
    ["Material / Main Resource", getDisplayValue(order.resource)],
    ["Quantity", getDisplayValue(order.quantity)],
    ["Output Quantity", getDisplayValue(order.outputQuantity)],
    ["Cut Quantity", getDisplayValue(order.cutQuantity)],
    [
      "Lamination / Finishing Quantity",
      getDisplayValue(order.laminationFinishingQuantity),
    ],
  ];

  if (order.status === "Waiting" || order.waitingReason?.trim()) {
    productionRows.push([
      "Waiting Reason",
      getDisplayValue(order.waitingReason, "Waiting Information"),
    ]);
  }

  for (const [label, value] of productionRows) {
    cursorY = drawFieldRow(doc, label, value, cursorY, contentWidth);
  }

  cursorY = drawSectionTitle(doc, "Links and Notes", cursorY + 4, contentWidth);

  const linkRows: Array<[string, string]> = [
    ["Main File Link", getDisplayValue(order.mainFileLink)],
    ["Artwork / Design Link", getDisplayValue(order.artworkDesignLink)],
    ["Final / Production Link", getDisplayValue(order.finalProductionLink)],
    ["Internal Notes", getDisplayValue(order.internalNotes, "No notes added")],
  ];

  for (const [label, value] of linkRows) {
    cursorY = drawFieldRow(doc, label, value, cursorY, contentWidth);
  }

  cursorY = drawSectionTitle(doc, "Reference / Attachment", cursorY + 4, contentWidth);

  const referenceUrl =
    order.referenceUrl?.trim() ?? "";
  cursorY = drawFieldRow(
    doc,
    "Reference URL",
    getDisplayValue(referenceUrl),
    cursorY,
    contentWidth
  );

  const referenceImage = order.referenceAttachmentUrl?.trim()
    ? await loadImageForPdf(order.referenceAttachmentUrl.trim()).catch(() => null)
    : null;

  if (referenceImage) {
    const maxImageWidth = contentWidth;
    const maxImageHeight = 220;
    const scale = Math.min(
      maxImageWidth / referenceImage.width,
      maxImageHeight / referenceImage.height,
      1
    );
    const imageWidth = referenceImage.width * scale;
    const imageHeight = referenceImage.height * scale;

    cursorY = ensureSpace(doc, cursorY, imageHeight + 24);
    doc.setDrawColor(226, 232, 240);
    doc.roundedRect(PAGE_MARGIN, cursorY, contentWidth, imageHeight + 16, 10, 10);
    doc.addImage(
      referenceImage.dataUrl,
      "PNG",
      PAGE_MARGIN + (contentWidth - imageWidth) / 2,
      cursorY + 8,
      imageWidth,
      imageHeight
    );
    cursorY += imageHeight + 24;

    cursorY = drawFieldRow(
      doc,
      "Reference Image Preview",
      "Preview embedded in this document.",
      cursorY,
      contentWidth
    );
  } else if (referenceUrl) {
    cursorY = drawFieldRow(
      doc,
      "Reference Image Preview",
      "Preview could not be embedded safely. Use the URL above to open the attachment.",
      cursorY,
      contentWidth
    );
  } else {
    cursorY = drawFieldRow(
      doc,
      "Reference Image Preview",
      "No attachment added",
      cursorY,
      contentWidth
    );
  }

  cursorY = drawSectionTitle(doc, "Timeline", cursorY + 4, contentWidth);

  const timelineRows: Array<[string, string]> = [
    ["Created At", getDisplayValue(formatDateTime(order.createdAt), "Not available")],
    ["Updated At", getDisplayValue(formatDateTime(order.updatedAt), "Not available")],
  ];

  if (order.completedAt) {
    timelineRows.push([
      "Completed At",
      getDisplayValue(formatDateTime(order.completedAt), "Not completed"),
    ]);
  }

  for (const [label, value] of timelineRows) {
    cursorY = drawFieldRow(doc, label, value, cursorY, contentWidth);
  }

  addFooter(doc);
  doc.save(buildFilename(order.id));
}
